const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";
const NEW_ATTACHEMENT = "NEW_ATTACHEMENT";
const NEW_MESSAGE_ALERT = "NEW_ATTACHEMENT_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const CHAT_ADMIN_TOKEN = "chat-admin-token";

const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHEMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  CHAT_ADMIN_TOKEN,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
};
